version: '3.4'

services:
  app:
    container_name: ze-app
    image: ze_app:latest
    build:
      context: ./
    ports:
      - "8080:8080"
    environment:
      MONGO_USER: root
      MONGO_PASSWORD: mongodb
      MONGO_HOST: mongo:27017
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodb

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongodb
      ME_CONFIG_MONGODB_URL: mongodb://root:mongodb@mongo:27017/
